# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Terzpegelmesser_Version1_6.ui'
#
# Created: Mon Jun 17 16:07:10 2013
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(872, 680)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.PlotTerzpegel = thirdPenStyles(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PlotTerzpegel.sizePolicy().hasHeightForWidth())
        self.PlotTerzpegel.setSizePolicy(sizePolicy)
        self.PlotTerzpegel.setMinimumSize(QtCore.QSize(200, 200))
        self.PlotTerzpegel.setObjectName(_fromUtf8("PlotTerzpegel"))
        self.horizontalLayout_17.addWidget(self.PlotTerzpegel)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.PlotKanalpegel = Channel_Bar(self.centralwidget)
        self.PlotKanalpegel.setMaximumSize(QtCore.QSize(150, 16777215))
        self.PlotKanalpegel.setObjectName(_fromUtf8("PlotKanalpegel"))
        self.horizontalLayout_7.addWidget(self.PlotKanalpegel)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.PlotWellenform = PlotWaveform(self.centralwidget)
        self.PlotWellenform.setMinimumSize(QtCore.QSize(200, 200))
        self.PlotWellenform.setObjectName(_fromUtf8("PlotWellenform"))
        self.horizontalLayout_11.addWidget(self.PlotWellenform)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.labelBew = QtGui.QLabel(self.centralwidget)
        self.labelBew.setObjectName(_fromUtf8("labelBew"))
        self.horizontalLayout_14.addWidget(self.labelBew)
        self.BoxBew = QtGui.QComboBox(self.centralwidget)
        self.BoxBew.setObjectName(_fromUtf8("BoxBew"))
        self.BoxBew.addItem(_fromUtf8(""))
        self.BoxBew.addItem(_fromUtf8(""))
        self.BoxBew.addItem(_fromUtf8(""))
        self.horizontalLayout_14.addWidget(self.BoxBew)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem)
        self.push_minus = QtGui.QPushButton(self.centralwidget)
        self.push_minus.setMaximumSize(QtCore.QSize(25, 28))
        self.push_minus.setObjectName(_fromUtf8("push_minus"))
        self.horizontalLayout_14.addWidget(self.push_minus)
        self.push_plus = QtGui.QPushButton(self.centralwidget)
        self.push_plus.setMaximumSize(QtCore.QSize(25, 28))
        self.push_plus.setObjectName(_fromUtf8("push_plus"))
        self.horizontalLayout_14.addWidget(self.push_plus)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.PlotSpektrogramm = MatplotlibWidget(self.tab_3)
        self.PlotSpektrogramm.setObjectName(_fromUtf8("PlotSpektrogramm"))
        self.horizontalLayout.addWidget(self.PlotSpektrogramm)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.PlotFFT = MatplotlibWidget(self.tab_4)
        self.PlotFFT.setObjectName(_fromUtf8("PlotFFT"))
        self.verticalLayout_4.addWidget(self.PlotFFT)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.labelFFT = QtGui.QLabel(self.tab_4)
        self.labelFFT.setObjectName(_fromUtf8("labelFFT"))
        self.horizontalLayout_16.addWidget(self.labelFFT)
        self.BoxFFT = QtGui.QComboBox(self.tab_4)
        self.BoxFFT.setObjectName(_fromUtf8("BoxFFT"))
        self.BoxFFT.addItem(_fromUtf8(""))
        self.BoxFFT.addItem(_fromUtf8(""))
        self.BoxFFT.addItem(_fromUtf8(""))
        self.BoxFFT.addItem(_fromUtf8(""))
        self.BoxFFT.addItem(_fromUtf8(""))
        self.BoxFFT.addItem(_fromUtf8(""))
        self.BoxFFT.addItem(_fromUtf8(""))
        self.BoxFFT.addItem(_fromUtf8(""))
        self.BoxFFT.addItem(_fromUtf8(""))
        self.horizontalLayout_16.addWidget(self.BoxFFT)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem1)
        self.labelScale = QtGui.QLabel(self.tab_4)
        self.labelScale.setObjectName(_fromUtf8("labelScale"))
        self.horizontalLayout_16.addWidget(self.labelScale)
        self.RadioLog = QtGui.QRadioButton(self.tab_4)
        self.RadioLog.setChecked(True)
        self.RadioLog.setObjectName(_fromUtf8("RadioLog"))
        self.horizontalLayout_16.addWidget(self.RadioLog)
        self.RadioLin = QtGui.QRadioButton(self.tab_4)
        self.RadioLin.setChecked(False)
        self.RadioLin.setObjectName(_fromUtf8("RadioLin"))
        self.horizontalLayout_16.addWidget(self.RadioLin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_15.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.tab_5)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.PlotGainVerlauf = GainPlotter(self.tab_5)
        self.PlotGainVerlauf.setObjectName(_fromUtf8("PlotGainVerlauf"))
        self.horizontalLayout_8.addWidget(self.PlotGainVerlauf)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.T = QtGui.QWidget()
        self.T.setObjectName(_fromUtf8("T"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.T)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.PlotTerzpegel_2 = thirdPenStyles(self.T)
        self.PlotTerzpegel_2.setObjectName(_fromUtf8("PlotTerzpegel_2"))
        self.horizontalLayout_10.addWidget(self.PlotTerzpegel_2)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_10)
        self.tabWidget.addTab(self.T, _fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.tabWidget)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.DeviceList = QtGui.QComboBox(self.centralwidget)
        self.DeviceList.setMaximumSize(QtCore.QSize(300, 30))
        self.DeviceList.setObjectName(_fromUtf8("DeviceList"))
        self.horizontalLayout_4.addWidget(self.DeviceList)
        self.ButtonStartStop = QtGui.QPushButton(self.centralwidget)
        self.ButtonStartStop.setMinimumSize(QtCore.QSize(100, 30))
        self.ButtonStartStop.setMaximumSize(QtCore.QSize(200, 30))
        self.ButtonStartStop.setObjectName(_fromUtf8("ButtonStartStop"))
        self.horizontalLayout_4.addWidget(self.ButtonStartStop)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 872, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuDatei = QtGui.QMenu(self.menubar)
        self.menuDatei.setObjectName(_fromUtf8("menuDatei"))
        self.menuTerzpegel = QtGui.QMenu(self.menubar)
        self.menuTerzpegel.setObjectName(_fromUtf8("menuTerzpegel"))
        self.menuBewertung = QtGui.QMenu(self.menuTerzpegel)
        self.menuBewertung.setObjectName(_fromUtf8("menuBewertung"))
        self.menuFFT = QtGui.QMenu(self.menubar)
        self.menuFFT.setObjectName(_fromUtf8("menuFFT"))
        self.menuFFT_L_nge = QtGui.QMenu(self.menuFFT)
        self.menuFFT_L_nge.setObjectName(_fromUtf8("menuFFT_L_nge"))
        self.menuSkalierung = QtGui.QMenu(self.menuFFT)
        self.menuSkalierung.setObjectName(_fromUtf8("menuSkalierung"))
        self.menuWavemeter = QtGui.QMenu(self.menubar)
        self.menuWavemeter.setObjectName(_fromUtf8("menuWavemeter"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionKeine = QtGui.QAction(MainWindow)
        self.actionKeine.setObjectName(_fromUtf8("actionKeine"))
        self.actionA = QtGui.QAction(MainWindow)
        self.actionA.setObjectName(_fromUtf8("actionA"))
        self.actionC = QtGui.QAction(MainWindow)
        self.actionC.setObjectName(_fromUtf8("actionC"))
        self.action32 = QtGui.QAction(MainWindow)
        self.action32.setObjectName(_fromUtf8("action32"))
        self.action64 = QtGui.QAction(MainWindow)
        self.action64.setObjectName(_fromUtf8("action64"))
        self.actionLinear = QtGui.QAction(MainWindow)
        self.actionLinear.setObjectName(_fromUtf8("actionLinear"))
        self.actionLogarithmic = QtGui.QAction(MainWindow)
        self.actionLogarithmic.setObjectName(_fromUtf8("actionLogarithmic"))
        self.actionZoom_In = QtGui.QAction(MainWindow)
        self.actionZoom_In.setObjectName(_fromUtf8("actionZoom_In"))
        self.actionZoom_Out = QtGui.QAction(MainWindow)
        self.actionZoom_Out.setObjectName(_fromUtf8("actionZoom_Out"))
        self.action128 = QtGui.QAction(MainWindow)
        self.action128.setObjectName(_fromUtf8("action128"))
        self.action256 = QtGui.QAction(MainWindow)
        self.action256.setObjectName(_fromUtf8("action256"))
        self.action512 = QtGui.QAction(MainWindow)
        self.action512.setObjectName(_fromUtf8("action512"))
        self.action1024 = QtGui.QAction(MainWindow)
        self.action1024.setObjectName(_fromUtf8("action1024"))
        self.action2048 = QtGui.QAction(MainWindow)
        self.action2048.setObjectName(_fromUtf8("action2048"))
        self.action4096 = QtGui.QAction(MainWindow)
        self.action4096.setObjectName(_fromUtf8("action4096"))
        self.action8192 = QtGui.QAction(MainWindow)
        self.action8192.setObjectName(_fromUtf8("action8192"))
        self.menuBewertung.addAction(self.actionKeine)
        self.menuBewertung.addAction(self.actionA)
        self.menuBewertung.addAction(self.actionC)
        self.menuTerzpegel.addAction(self.menuBewertung.menuAction())
        self.menuFFT_L_nge.addAction(self.action32)
        self.menuFFT_L_nge.addAction(self.action64)
        self.menuFFT_L_nge.addAction(self.action128)
        self.menuFFT_L_nge.addAction(self.action256)
        self.menuFFT_L_nge.addAction(self.action512)
        self.menuFFT_L_nge.addAction(self.action1024)
        self.menuFFT_L_nge.addAction(self.action2048)
        self.menuFFT_L_nge.addAction(self.action4096)
        self.menuFFT_L_nge.addAction(self.action8192)
        self.menuSkalierung.addAction(self.actionLinear)
        self.menuSkalierung.addAction(self.actionLogarithmic)
        self.menuFFT.addAction(self.menuFFT_L_nge.menuAction())
        self.menuFFT.addAction(self.menuSkalierung.menuAction())
        self.menuWavemeter.addAction(self.actionZoom_In)
        self.menuWavemeter.addAction(self.actionZoom_Out)
        self.menubar.addAction(self.menuDatei.menuAction())
        self.menubar.addAction(self.menuTerzpegel.menuAction())
        self.menubar.addAction(self.menuFFT.menuAction())
        self.menubar.addAction(self.menuWavemeter.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.labelBew.setText(QtGui.QApplication.translate("MainWindow", "Weighting", None, QtGui.QApplication.UnicodeUTF8))
        self.BoxBew.setItemText(0, QtGui.QApplication.translate("MainWindow", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.BoxBew.setItemText(1, QtGui.QApplication.translate("MainWindow", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.BoxBew.setItemText(2, QtGui.QApplication.translate("MainWindow", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.push_minus.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.push_plus.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Spektrogramm", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFFT.setText(QtGui.QApplication.translate("MainWindow", "FFT Length", None, QtGui.QApplication.UnicodeUTF8))
        self.BoxFFT.setItemText(0, QtGui.QApplication.translate("MainWindow", "32", None, QtGui.QApplication.UnicodeUTF8))
        self.BoxFFT.setItemText(1, QtGui.QApplication.translate("MainWindow", "64", None, QtGui.QApplication.UnicodeUTF8))
        self.BoxFFT.setItemText(2, QtGui.QApplication.translate("MainWindow", "128", None, QtGui.QApplication.UnicodeUTF8))
        self.BoxFFT.setItemText(3, QtGui.QApplication.translate("MainWindow", "256", None, QtGui.QApplication.UnicodeUTF8))
        self.BoxFFT.setItemText(4, QtGui.QApplication.translate("MainWindow", "512", None, QtGui.QApplication.UnicodeUTF8))
        self.BoxFFT.setItemText(5, QtGui.QApplication.translate("MainWindow", "1024", None, QtGui.QApplication.UnicodeUTF8))
        self.BoxFFT.setItemText(6, QtGui.QApplication.translate("MainWindow", "2048", None, QtGui.QApplication.UnicodeUTF8))
        self.BoxFFT.setItemText(7, QtGui.QApplication.translate("MainWindow", "4096", None, QtGui.QApplication.UnicodeUTF8))
        self.BoxFFT.setItemText(8, QtGui.QApplication.translate("MainWindow", "8192", None, QtGui.QApplication.UnicodeUTF8))
        self.labelScale.setText(QtGui.QApplication.translate("MainWindow", "Scaling", None, QtGui.QApplication.UnicodeUTF8))
        self.RadioLog.setText(QtGui.QApplication.translate("MainWindow", "logarithmic", None, QtGui.QApplication.UnicodeUTF8))
        self.RadioLin.setText(QtGui.QApplication.translate("MainWindow", "linear", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "FFT", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "Gain-Verlauf", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.T), QtGui.QApplication.translate("MainWindow", "Terzpegel", None, QtGui.QApplication.UnicodeUTF8))
        self.ButtonStartStop.setText(QtGui.QApplication.translate("MainWindow", "START/STOP", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDatei.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTerzpegel.setTitle(QtGui.QApplication.translate("MainWindow", "Thirds", None, QtGui.QApplication.UnicodeUTF8))
        self.menuBewertung.setTitle(QtGui.QApplication.translate("MainWindow", "Weighting", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFFT.setTitle(QtGui.QApplication.translate("MainWindow", "FFT", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFFT_L_nge.setTitle(QtGui.QApplication.translate("MainWindow", "FFT Length", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSkalierung.setTitle(QtGui.QApplication.translate("MainWindow", "Scaling", None, QtGui.QApplication.UnicodeUTF8))
        self.menuWavemeter.setTitle(QtGui.QApplication.translate("MainWindow", "Wavemeter", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKeine.setText(QtGui.QApplication.translate("MainWindow", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.actionA.setText(QtGui.QApplication.translate("MainWindow", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionC.setText(QtGui.QApplication.translate("MainWindow", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.action32.setText(QtGui.QApplication.translate("MainWindow", "32", None, QtGui.QApplication.UnicodeUTF8))
        self.action64.setText(QtGui.QApplication.translate("MainWindow", "64", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLinear.setText(QtGui.QApplication.translate("MainWindow", "linear", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLogarithmic.setText(QtGui.QApplication.translate("MainWindow", "logarithmic", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_In.setText(QtGui.QApplication.translate("MainWindow", "Zoom In", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_Out.setText(QtGui.QApplication.translate("MainWindow", "Zoom Out", None, QtGui.QApplication.UnicodeUTF8))
        self.action128.setText(QtGui.QApplication.translate("MainWindow", "128", None, QtGui.QApplication.UnicodeUTF8))
        self.action256.setText(QtGui.QApplication.translate("MainWindow", "256", None, QtGui.QApplication.UnicodeUTF8))
        self.action512.setText(QtGui.QApplication.translate("MainWindow", "512", None, QtGui.QApplication.UnicodeUTF8))
        self.action1024.setText(QtGui.QApplication.translate("MainWindow", "1024", None, QtGui.QApplication.UnicodeUTF8))
        self.action2048.setText(QtGui.QApplication.translate("MainWindow", "2048", None, QtGui.QApplication.UnicodeUTF8))
        self.action4096.setText(QtGui.QApplication.translate("MainWindow", "4096", None, QtGui.QApplication.UnicodeUTF8))
        self.action8192.setText(QtGui.QApplication.translate("MainWindow", "8192", None, QtGui.QApplication.UnicodeUTF8))

from plot_channellevel import Channel_Bar
from matplotlibwidget import MatplotlibWidget
from plot_gain import GainPlotter
from plot_waveform import PlotWaveform
from plot_terzpegel import thirdPenStyles
